-- MySQL Script generated by MySQL Workbench
-- Fri Mar 14 23:37:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tarea_semana_5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tarea_semana_5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarea_semana_5` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tarea_semana_5` ;

-- -----------------------------------------------------
-- Table `tarea_semana_5`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`autores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `biografia` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`control_de_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`control_de_inventario` (
  `idcontrol_de_inventario` INT NOT NULL,
  `total_ejemplares` INT NULL DEFAULT NULL,
  `ejemplares_prestados` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idcontrol_de_inventario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`libros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `num_paginas` INT NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `editorial` VARCHAR(255) NOT NULL,
  `inventario_id_inventario` INT NOT NULL,
  `libros_id` INT NOT NULL,
  `libros_inventario_id_inventario` INT NOT NULL,
  `prestamo_libro_id_libro` INT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`id`, `inventario_id_inventario`, `prestamo_libro_id_libro`),
  UNIQUE INDEX `isbn` (`isbn` ASC) VISIBLE,
  INDEX `fk_libros_libros1_idx` (`libros_id` ASC, `libros_inventario_id_inventario` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_libros_libros1`
    FOREIGN KEY (`libros_id` , `libros_inventario_id_inventario`)
    REFERENCES `tarea_semana_5`.`libros` (`id` , `inventario_id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`inventario` (
  `libro_id` INT NOT NULL,
  `cantidad_total` INT NOT NULL,
  `cantidad_prestada` INT NULL DEFAULT '0',
  PRIMARY KEY (`libro_id`),
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `tarea_semana_5`.`libros` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`lectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`lectores` (
  `id_lector` INT NOT NULL,
  `nombre completo` VARCHAR(200) NULL DEFAULT NULL,
  `correo electrónico` VARCHAR(200) NULL DEFAULT NULL,
  `número telefónico` VARCHAR(45) NULL DEFAULT NULL,
  `prestamos_id_prestamo` INT NOT NULL,
  PRIMARY KEY (`id_lector`, `prestamos_id_prestamo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`libros_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`libros_autores` (
  `libro_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  PRIMARY KEY (`libro_id`, `autor_id`),
  INDEX `autor_id` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `libros_autores_ibfk_1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `tarea_semana_5`.`libros` (`id`),
  CONSTRAINT `libros_autores_ibfk_2`
    FOREIGN KEY (`autor_id`)
    REFERENCES `tarea_semana_5`.`autores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`libros_has_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`libros_has_autores` (
  `libros_id_libro` INT NOT NULL,
  `autores_id_autor` INT NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`prestamo_libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`prestamo_libro` (
  `prestamos_id_prestamo_prestamo` INT NOT NULL,
  `libros_id_libro` INT NOT NULL,
  `libros_inventario_id_inventarario` INT NOT NULL,
  `libros_id` INT NOT NULL,
  `libros_inventario_id_inventario` INT NOT NULL,
  `libros_prestamo_libro_id_libro` INT NOT NULL,
  UNIQUE INDEX `prestamos_id_prestamo_prestamo_UNIQUE` (`prestamos_id_prestamo_prestamo` ASC) VISIBLE,
  INDEX `fk_prestamo_libro_libros1_idx` (`libros_id` ASC, `libros_inventario_id_inventario` ASC, `libros_prestamo_libro_id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_libro_libros1`
    FOREIGN KEY (`libros_id` , `libros_inventario_id_inventario` , `libros_prestamo_libro_id_libro`)
    REFERENCES `tarea_semana_5`.`libros` (`id` , `inventario_id_inventario` , `prestamo_libro_id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(255) NOT NULL,
  `correo_electronico` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `prestamos_id_prestamo` INT NOT NULL,
  PRIMARY KEY (`id`, `prestamos_id_prestamo`),
  UNIQUE INDEX `correo_electronico` (`correo_electronico` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`prestamos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL DEFAULT NULL,
  `libro_id` INT NULL DEFAULT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_limite` DATE NOT NULL,
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'entregado', 'retrasado') NULL DEFAULT 'pendiente',
  `prestamos_id_prestamo` INT NOT NULL,
  PRIMARY KEY (`id`, `prestamos_id_prestamo`),
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `libro_id` (`libro_id` ASC) VISIBLE,
  CONSTRAINT `prestamos_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tarea_semana_5`.`usuarios` (`id`),
  CONSTRAINT `prestamos_ibfk_2`
    FOREIGN KEY (`libro_id`)
    REFERENCES `tarea_semana_5`.`libros` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`préstamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`préstamos` (
  `idpréstamo` INT NOT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_límite` DATE NULL DEFAULT NULL,
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idpréstamo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`registro_ de_ libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`registro_ de_ libros` (
  `idregistro_de_libros` INT NOT NULL,
  `título del libro` VARCHAR(160) NULL DEFAULT NULL,
  `fecha de publicación` DATE NULL DEFAULT NULL,
  `número de páginas` VARCHAR(100) NULL DEFAULT NULL,
  `ISBN` VARCHAR(200) NULL DEFAULT NULL,
  `editorial` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idregistro_de_libros`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '\\n\\n\\n\\n\\n\\n';


-- -----------------------------------------------------
-- Table `tarea_semana_5`.`registro_de_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea_semana_5`.`registro_de_autores` (
  `idregistro_de_autores` INT NOT NULL,
  `nombre completo` VARCHAR(130) NULL DEFAULT NULL,
  `fecha de nacimiento` DATE NULL DEFAULT NULL,
  `biografía` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idregistro_de_autores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
